FROM node:latest

WORKDIR /app

COPY . /app
RUN npm install

ARG PORT=3000
ENV PORT=$PORT

ENV DB_DATABASE=utp_dex, DB_USER=root, DB_PASS=gpEp63bvAOd5oA4y, INSTANCE_CONNECTION_NAME=$INSTANCE_CONNECTION_NAME

EXPOSE 3000

CMD ["npm", "start"]