FROM launcher.gcr.io/google/nodejs

WORKDIR /app

COPY . /app
RUN npm install

ARG PORT=3000
ENV PORT=$PORT

ENV DB_DATABASE=$DB_DATABASE, DB_USER=$DB_USER, DB_PASS=$DB_PASS, INSTANCE_CONNECTION_NAME=$INSTANCE_CONNECTION_NAME

EXPOSE 3000

CMD ["npm", "start"]