FROM node:latest

WORKDIR /app

COPY . /app
RUN npm install

ARG PORT=3000
ENV PORT=$PORT

ENV DB_DATABASE=$DB_DATABASE, DB_USER=$DB_USER, DB_PASS=$DB_PASS, INSTANCE_CONNECTION_NAME=12345

EXPOSE 3000

CMD ["npm", "start"]